cmake_minimum_required(VERSION 4.0)
project(LeetCode)

set(CMAKE_CXX_STANDARD 20)

add_executable(LeetCode main.cpp)

add_executable(704_BinarySearch DaiMaSuiXiangLu/Array/704_BinarySearch.cpp)
add_executable(27_RemoveElement DaiMaSuiXiangLu/Array/27_RemoveElement.cpp)
add_executable(977_SortedArraySquare DaiMaSuiXiangLu/Array/977_SortedArraySquare.cpp)
add_executable(209_minSubArrayLen DaiMaSuiXiangLu/Array/209_minSubArrayLen.cpp)
add_executable(59_generateMatrix DaiMaSuiXiangLu/Array/59_generateMatrix.cpp)
add_executable(KMP DaiMaSuiXiangLu/String/KMP.cpp)
add_executable(Kama99_IslandCounting DaiMaSuiXiangLu/Graph/Kama/Kama99_IslandCountingBFS.cpp)
add_executable(Kama99_IslandCountingDFS DaiMaSuiXiangLu/Graph/Kama/Kama99_IslandCountingDFS.cpp)
add_executable(Kama100_BiggestIsland DaiMaSuiXiangLu/Graph/Kama/Kama100_BiggestIsland.cpp)
add_executable(Kama101_SingleIslandArea DaiMaSuiXiangLu/Graph/Kama/Kama101_SingleIslandArea.cpp)
add_executable(Kama102_SinkingIsland DaiMaSuiXiangLu/Graph/Kama/Kama102_SinkingIsland.cpp)
add_executable(Kama103_Flow DaiMaSuiXiangLu/Graph/Kama/Kama103_Flow.cpp)
add_executable(Kama104_BuildBiggestIsland DaiMaSuiXiangLu/Graph/Kama/Kama104_BuildBiggestIsland.cpp)
add_executable(Kama105_DirectedGraphConnected DaiMaSuiXiangLu/Graph/Kama/Kama105_DirectedGraphConnected.cpp)
add_executable(Kama110_StrChange DaiMaSuiXiangLu/Graph/Kama/Kama110_StrChange.cpp)
add_executable(Kama106_CoastLength DaiMaSuiXiangLu/Graph/Kama/Kama106_CoastLength.cpp)
add_executable(Kama107_FindExistedPath DaiMaSuiXiangLu/Graph/Kama/Kama107_FindExistedPath.cpp)
add_executable(Kama108_RedundantEdges DaiMaSuiXiangLu/Graph/Kama/Kama108_RedundantEdges.cpp)
add_executable(Prim DaiMaSuiXiangLu/Graph/Prim.cpp)
add_executable(Kama53_TreasurePrim DaiMaSuiXiangLu/Graph/Kama/Kama53_TreasurePrim.cpp)
add_executable(Kruskal DaiMaSuiXiangLu/Graph/Kruskal.cpp)
add_executable(Kama53_TreasureKruskal DaiMaSuiXiangLu/Graph/Kama/Kama53_TreasureKruskal.cpp)
add_executable(TopologicalSorting DaiMaSuiXiangLu/Graph/TopologicalSorting.cpp)
add_executable(Kama47_JoinMeeting DaiMaSuiXiangLu/Graph/Kama/Kama47_JoinMeeting.cpp)
add_executable(Kama47_JoinMeetingHeap DaiMaSuiXiangLu/Graph/Kama/Kama47_JoinMeetingHeap.cpp)
add_executable(BellmanFord DaiMaSuiXiangLu/Graph/BellmanFord.cpp)
add_executable(Kama94_CityTransmitI DaiMaSuiXiangLu/Graph/Kama/Kama94_CityTransmitI.cpp)
add_executable(Kama94_CityTransmitIQueue DaiMaSuiXiangLu/Graph/Kama/Kama94_CityTransmitIQueue.cpp)
add_executable(Kama95_CityTransmitII DaiMaSuiXiangLu/Graph/Kama/Kama95_CityTransmitII.cpp)
add_executable(Kama96_CityTransmitIII DaiMaSuiXiangLu/Graph/Kama/Kama96_CityTransmitIII.cpp)
add_executable(Floyd DaiMaSuiXiangLu/Graph/Floyd.cpp)
add_executable(Floyd_DistAndNext DaiMaSuiXiangLu/Graph/Floyd_DistAndNext.cpp)
add_executable(Kama97_WalkingInPark DaiMaSuiXiangLu/Graph/Kama/Kama97_WalkingInPark.cpp)
add_executable(AStar DaiMaSuiXiangLu/Graph/AStar.cpp)
add_executable(Kama127_KnightAttack DaiMaSuiXiangLu/Graph/Kama/Kama127_KnightAttack.cpp)